site_name: OpenLUST

nav:
  - Home: index.md
  - "LUST-motion":
      - lustmotion-getstarted.md
      - lustmotion-config.md
      - lustmotion-usage.md
      - lustmotion-connectivity.md
      - lustmotion-API.md
      - lustmotion-contribute.md
  - "LUST-Remote":
      - lrgetstarted.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - toc.integrate
    - navigation.top
    - content.code.copy
    - search.highlight

  plugins:
    - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_url: https://github.com/openlust/docs
